language: node_js
node_js:
   - node # will use latest node

sudo: required
dist: trusty
addons:
  chrome: stable
branches:
    only:
    - master
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
    - npm install -g --silent @angular/cli
script: # the build step
   - npm run prod:build
   - ng build --prod --base-href "https://HackPoint.github.io/ng-apps/"
   - npm test
   - npm run testbe
notifications:
  email: # only receive email when the build status changes (someone broke the build!)
    on_failure: change
    on_success: change
after_success:
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false"
notifications:
  email:
    - genash@gmail.com
on_success: always # default: change
on_failure: always # default: always
